# Generated by Django 5.2 on 2025-04-18 10:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
        ('tour_package', '0007_alter_tourpackage_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='expensereport',
            options={'verbose_name': 'Expense Report', 'verbose_name_plural': 'Expense Reports'},
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the expense amount (e.g., 50.00).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='Select the expense category.', on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.expensecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Currency conversion rate (e.g., 1.0 for no conversion).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Conversion Rate'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(help_text='Select the date the expense was incurred.', verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the expense.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tour_package',
            field=models.ForeignKey(blank=True, help_text='Optional associated tour package.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_package.tourpackage', verbose_name='Tour Package'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this expense.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(help_text='Enter the name of the expense category (e.g., Food, Transport).', max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='end_date',
            field=models.DateField(help_text='Select the end date of the report period.', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='start_date',
            field=models.DateField(help_text='Select the start date of the report period.', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, help_text='Total expenses for the report period.', max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Expenses'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='tour_package',
            field=models.ForeignKey(help_text='Associated tour package for this report.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='tour_package.tourpackage', verbose_name='Tour Package'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='user',
            field=models.ForeignKey(help_text='Select the user who generated this report.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterModelTable(
            name='expense',
            table='expense_tracker_expense',
        ),
        migrations.AlterModelTable(
            name='expensecategory',
            table='expense_tracker_expensecategory',
        ),
        migrations.AlterModelTable(
            name='expensereport',
            table='expense_tracker_expensereport',
        ),
    ]
