# Generated by Django 5.2 on 2025-04-22 07:37

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_alter_expense_options_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Optional description of the expense.', null=True, verbose_name='Description'),
        ),
    ]
