# Generated by Django 5.2 on 2025-04-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0014_alter_guide_image'),
        ('expense_tracker', '0003_alter_expense_description'),
        ('hotelbooking', '0004_alter_guide_experience_years_alter_guide_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Guides',
            field=models.ForeignKey(blank=True, help_text='Optional associated tour package.', null=True, on_delete=django.db.models.deletion.CASCADE, to='Guides.guide', verbose_name='Guides'),
        ),
        migrations.AddField(
            model_name='expense',
            name='hotelbooking',
            field=models.ForeignKey(blank=True, help_text='Optional associated tour package.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.hotelbooking', verbose_name='hotelbooking'),
        ),
    ]
