# Generated by Django 5.1.6 on 2025-03-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
