# Generated by Django 5.2 on 2025-04-10 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0003_alter_tourpackage_date_alter_tourpackage_description'),
        ('tourism_company', '0003_tourismcompany_is_active_tourismcompany_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='company_name',
        ),
       # In your 0004 migration file
        migrations.AddField(
            model_name='tourpackage',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism_company.tourismcompany', related_name='tour_packages'),
        ),

        migrations.AlterModelTable(
            name='tourpackage',
            table='TourPackage',
        ),
    ]
