# Generated by Django 5.2 on 2025-04-10 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0006_alter_tourpackage_company'),
        ('tourism_company', '0003_tourismcompany_is_active_tourismcompany_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism_company.tourismcompany'),
        ),
    ]
