# Generated by Django 5.2 on 2025-04-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0007_alter_tourpackage_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'verbose_name': 'Tour Package', 'verbose_name_plural': 'Tour Packages'},
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Price of the tour package.', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='city',
            field=models.CharField(help_text='City where the tour takes place.', max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='company',
            field=models.CharField(blank=True, help_text='Name of the tourism company offering this package.', max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='country',
            field=models.CharField(help_text='Country where the tour takes place.', max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the tour package was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='date',
            field=models.DateField(help_text='Date the tour package is scheduled for.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='description',
            field=models.TextField(help_text='Detailed description of the tour package.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration',
            field=models.IntegerField(help_text='Duration of the tour package in days.', verbose_name='Duration (Days)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='package_id',
            field=models.AutoField(help_text='Unique identifier for the tour package.', primary_key=True, serialize=False, verbose_name='Package ID'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='package_name',
            field=models.CharField(help_text='Name of the tour package.', max_length=255, verbose_name='Package Name'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='tour_type',
            field=models.CharField(help_text='Type of tour (e.g., Adventure, Family, Cultural).', max_length=255, verbose_name='Tour Type'),
        ),
        migrations.AlterModelTable(
            name='tourpackage',
            table='tour_packages',
        ),
    ]
