# Generated by Django 5.2 on 2025-04-22 07:37

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0008_alter_tourpackage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', fernet_fields.fields.EncryptedCharField(max_length=100)),
                ('address', fernet_fields.fields.EncryptedTextField()),
                ('contact_number', fernet_fields.fields.EncryptedCharField(max_length=15)),
                ('email', fernet_fields.fields.EncryptedEmailField(max_length=254)),
                ('website', fernet_fields.fields.EncryptedCharField(max_length=200)),
                ('created_at', fernet_fields.fields.EncryptedDateTimeField(auto_now_add=True)),
                ('updated_at', fernet_fields.fields.EncryptedDateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='city',
            field=fernet_fields.fields.EncryptedCharField(help_text='City where the tour takes place.', max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='country',
            field=fernet_fields.fields.EncryptedCharField(help_text='Country where the tour takes place.', max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='created_at',
            field=fernet_fields.fields.EncryptedDateTimeField(auto_now_add=True, help_text='Timestamp when the tour package was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='description',
            field=fernet_fields.fields.EncryptedTextField(help_text='Detailed description of the tour package.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='package_name',
            field=fernet_fields.fields.EncryptedCharField(help_text='Name of the tour package.', max_length=255, verbose_name='Package Name'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='tour_type',
            field=fernet_fields.fields.EncryptedCharField(help_text='Type of tour (e.g., Adventure, Family, Cultural).', max_length=255, verbose_name='Tour Type'),
        ),
    ]
