# Generated by Django 5.2 on 2025-04-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0009_tourismcompany_alter_tourpackage_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indicates if the tour package has been approved.', verbose_name='Is Approved'),
        ),
    ]
