# Generated by Django 5.2 on 2025-05-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0010_tourpackage_is_approved'),
        ('tourism_company', '0007_alter_tourismcompany_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='company',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tourism_company',
            field=models.ForeignKey(default='English', help_text='Tourism company offering this package.', on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='tourism_company.tourismcompany', verbose_name='Tourism Company'),
            preserve_default=False,
        ),
    ]
