# Generated by Django 5.2 on 2025-05-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0011_remove_tourpackage_company_and_more'),
        ('tourism_company', '0009_alter_tourismcompany_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='tourism_company',
            field=models.ForeignKey(db_column='company_id', help_text='Tourism company offering this package.', on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='tourism_company.tourismcompany', verbose_name='Tourism Company'),
        ),
    ]
