# Generated by Django 5.2 on 2025-05-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0012_remove_tourpackage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the tour package was created.', null=True, verbose_name='Created At'),
        ),
    ]
