# Generated by Django 5.2 on 2025-05-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0012_alter_tourpackage_created_at_and_more'),
        ('tour_package', '0013_tourpackage_created_at'),
    ]

    operations = [
    ]
