# Generated by Django 5.2 on 2025-04-20 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the language.', max_length=100, unique=True, verbose_name='Language Name')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload an image representing the location.', upload_to='location_profiles/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Rating of the location, on a scale of 0 to 5.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text="URL-friendly version of the location's name for SEO purposes.", unique=True, verbose_name='Location Slug'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude of the location. Must be between -90 and 90.', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Longitude of the location. Must be between -180 and 180.', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Enter the name of the location, e.g., City or Landmark.', max_length=255, verbose_name='Location Name'),
        ),
        migrations.AddField(
            model_name='location',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Languages spoken in this location. Choose from available languages.', related_name='locations', to='maps.language', verbose_name='Languages Spoken'),
        ),
    ]
