# Generated by Django 5.2 on 2025-04-22 07:37

import apps.maps.models
import django.core.validators
import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_language_location_profile_picture_location_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=apps.maps.models.EncryptedDecimalField(help_text='Latitude of the location. Must be between -90 and 90.', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=apps.maps.models.EncryptedDecimalField(help_text='Longitude of the location. Must be between -180 and 180.', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=fernet_fields.fields.EncryptedCharField(help_text='Enter the name of the location, e.g., City or Landmark.', max_length=255, verbose_name='Location Name'),
        ),
    ]
