# Generated by Django 5.1.6 on 2025-04-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0006_remove_user_user_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trip',
            table='Trip',
        ),
    ]
