# Generated by Django 5.1.6 on 2025-04-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0007_alter_trip_table'),
    ]

    operations = [
    ]
