# Generated by Django 5.2 on 2025-04-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0009_alter_booking_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginadmin',
            table='Admin',
        ),
    ]
