# Generated by Django 5.2 on 2025-04-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0010_alter_loginadmin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
    ]
