# Generated by Django 5.2 on 2025-04-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0013_alter_bookingdetail_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingDetail',
        ),
    ]
