# Generated by Django 5.2 on 2025-04-20 07:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0008_alter_tourpackage_options_and_more'),
        ('user_login', '0014_delete_bookingdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the language.', max_length=50, unique=True, verbose_name='Language Name')),
            ],
            options={
                'db_table': 'Language',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='Enter the notification message.', verbose_name='Notification Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deal', 'Deal'), ('flight', 'Flight Change'), ('safety', 'Safety Update')], max_length=50, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(help_text='Enter the destination of the trip.', max_length=100, verbose_name='Destination Name'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(help_text='Enter the trip end date.', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(help_text='Enter the trip start date.', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=20, verbose_name='Trip Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text="Enter user's address.", max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="User's bio for profile.", null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(help_text="Enter user's date of birth.", verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address.', max_length=55, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text="Enter the user's full name.", max_length=100, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password will be hashed before saving.', max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter a phone number.', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], default='married', max_length=20, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Choose the preferred theme.', max_length=50, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description of the destination.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='destination_name',
            field=models.CharField(help_text='Enter the destination name.', max_length=100, verbose_name='Destination Name'),
        ),
        migrations.AlterModelTable(
            name='loginadmin',
            table='LoginAdmin',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='tour_package.tourpackage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='user_login.user')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Enter the guide's name.", max_length=100, verbose_name='Guide Name')),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug.', unique=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload profile picture.', upload_to='guide_profiles/')),
                ('rating', models.FloatField(default=0.0, help_text='Rating of the guide (0-5).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating')),
                ('languages', models.ManyToManyField(blank=True, help_text='Languages spoken by the guide.', related_name='guides', to='user_login.language', verbose_name='Languages')),
            ],
            options={
                'verbose_name': 'Tour Guide',
                'verbose_name_plural': 'Tour Guides',
                'db_table': 'Guide',
            },
        ),
    ]
