# Generated by Django 5.2 on 2025-04-22 07:37

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0015_language_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginadmin',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=fernet_fields.fields.EncryptedTextField(help_text='Enter the notification message.', verbose_name='Notification Message'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(help_text='Password will be hashed before saving.', max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='description',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Enter a description of the destination.', null=True, verbose_name='Description'),
        ),
    ]
