# Generated by Django 5.2 on 2025-04-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0016_alter_loginadmin_password_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginadmin',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
