# Generated by Django 5.2 on 2025-04-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0017_alter_loginadmin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password will be hashed before saving.', max_length=255, verbose_name='Password'),
        ),
    ]
