# Generated by Django 5.1.6 on 2025-03-26 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_community', '0001_initial'),
        ('user_login', '0004_remove_booking_user_id_booking_user_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_login.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'group_posts',
            },
        ),
    ]
