# Generated by Django 5.1.6 on 2025-04-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_community', '0004_tag_alter_follow_table_discussiongroup_grouppost_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
    ]
