# Generated by Django 5.1.6 on 2025-04-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_community', '0006_post_group_alter_category_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
