# Generated by Django 5.2 on 2025-04-22 07:37

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_community', '0007_remove_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=fernet_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=fernet_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='content',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='created_at',
            field=fernet_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='description',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='name',
            field=fernet_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=fernet_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='content',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='created_at',
            field=fernet_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=fernet_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=fernet_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='created_at',
            field=fernet_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=fernet_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=fernet_fields.fields.EncryptedCharField(max_length=100),
        ),
    ]
