# Generated by Django 5.2 on 2025-04-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_community', '0008_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discussiongroup',
            table='discussion_groups',
        ),
    ]
