# Generated by Django 5.1.6 on 2025-04-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_community', '0005_alter_follow_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_community.discussiongroup'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
