# Generated by Django 5.1.6 on 2025-03-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0002_alter_guide_expertise_alter_guide_guide_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='expertise',
            field=models.TextField(),
        ),
    ]
