# Generated by Django 5.2 on 2025-04-13 13:56

import apps.hotelbooking.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0001_initial'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='amenity',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('ac', 'Air Conditioning'), ('breakfast', 'Breakfast'), ('pool', 'Swimming Pool'), ('parking', 'Parking'), ('gym', 'Gym'), ('spa', 'Spa'), ('tv', 'Television'), ('minibar', 'Minibar')], default='wifi', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.location'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='notify_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='rooms_available',
            field=models.BooleanField(default=True, verbose_name='Rooms Available'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='arrive_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkout_time',
            field=models.DateTimeField(default=apps.hotelbooking.models.default_checkout_time),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_type',
            field=models.CharField(choices=[('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Standard', 'Standard')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='total_person',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='HotelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Revenue', 'Revenue'), ('Availability', 'Room Availability')], max_length=50)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('report_data', models.JSONField()),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hotelbooking.hotelbooking')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Standard', 'Standard')], max_length=100)),
                ('room_number', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Occupied', 'Occupied')], default='Available', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotelbooking.hotelbooking')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='hotelbooking.hotelroom')),
            ],
        ),
    ]
