# Generated by Django 5.2 on 2025-04-20 07:48

import apps.hotelbooking.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0002_hotelrevenue_hotelbooking_amenity_hotelbooking_email_and_more'),
        ('maps', '0002_language_location_profile_picture_location_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Language Name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={'verbose_name': 'Hotel Booking', 'verbose_name_plural': 'Hotel Bookings'},
        ),
        migrations.AlterModelOptions(
            name='hotelreport',
            options={'verbose_name': 'Hotel Report', 'verbose_name_plural': 'Hotel Reports'},
        ),
        migrations.AlterModelOptions(
            name='hotelrevenue',
            options={'verbose_name': 'Hotel Revenue', 'verbose_name_plural': 'Hotel Revenues'},
        ),
        migrations.AlterModelOptions(
            name='hotelroom',
            options={'verbose_name': 'Hotel Room', 'verbose_name_plural': 'Hotel Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomavailability',
            options={'verbose_name': 'Room Availability', 'verbose_name_plural': 'Room Availabilities'},
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='amenity',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('ac', 'Air Conditioning'), ('breakfast', 'Breakfast'), ('pool', 'Swimming Pool'), ('parking', 'Parking'), ('gym', 'Gym'), ('spa', 'Spa'), ('tv', 'Television'), ('minibar', 'Minibar')], max_length=100, verbose_name='Hotel Amenity'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='arrive_time',
            field=models.DateTimeField(verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkout_time',
            field=models.DateTimeField(default=apps.hotelbooking.models.default_checkout_time, verbose_name='Checkout Time'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_address',
            field=models.CharField(max_length=255, verbose_name='Hotel Address'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Hotel ID'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_name',
            field=models.CharField(max_length=255, verbose_name='Hotel Name'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.location', verbose_name='Hotel Location'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='notify_admin',
            field=models.BooleanField(default=False, verbose_name='Notify Admin'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_photos/', verbose_name='Hotel Photo'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_type',
            field=models.CharField(choices=[('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Standard', 'Standard')], max_length=100, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='Booking Status'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='total_person',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Persons'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='hotelreport',
            name='hotel_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hotelbooking.hotelbooking', verbose_name='Hotel Booking'),
        ),
        migrations.AlterField(
            model_name='hotelreport',
            name='report_data',
            field=models.JSONField(verbose_name='Report Data'),
        ),
        migrations.AlterField(
            model_name='hotelreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Report Date'),
        ),
        migrations.AlterField(
            model_name='hotelreport',
            name='report_type',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Availability', 'Room Availability')], max_length=50, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='hotelrevenue',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='hotelrevenue',
            name='hotel_name',
            field=models.CharField(max_length=255, verbose_name='Hotel Name'),
        ),
        migrations.AlterField(
            model_name='hotelrevenue',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Room Description'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotelbooking.hotelbooking', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price per Night'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_number',
            field=models.CharField(max_length=100, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Standard', 'Standard')], max_length=100, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Occupied', 'Occupied')], default='Available', max_length=50, verbose_name='Room Status'),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='available_date',
            field=models.DateField(verbose_name='Available Date'),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is Available'),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='hotelbooking.hotelroom', verbose_name='Room'),
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the guide.', max_length=255, unique=True, verbose_name='Full Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture.', upload_to='guide_profiles/', verbose_name='Profile Picture')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating')),
                ('experience_years', models.IntegerField(help_text='Enter years of experience.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Years of Experience')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
                ('languages', models.ManyToManyField(help_text='Select the languages spoken by the guide.', to='hotelbooking.language', verbose_name='Languages Spoken')),
            ],
            options={
                'verbose_name': 'Guide',
                'verbose_name_plural': 'Guides',
            },
        ),
    ]
