# Generated by Django 5.2 on 2025-04-22 07:37

import apps.hotelbooking.models
import django.core.validators
import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0003_language_alter_hotelbooking_options_and_more'),
        ('maps', '0003_alter_location_latitude_alter_location_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='experience_years',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='languages',
            field=models.ManyToManyField(to='hotelbooking.language', verbose_name='Languages Spoken'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='guide_profiles/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='amenity',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('ac', 'Air Conditioning'), ('breakfast', 'Breakfast'), ('pool', 'Swimming Pool'), ('parking', 'Parking'), ('gym', 'Gym'), ('spa', 'Spa'), ('tv', 'Television'), ('minibar', 'Minibar')], max_length=100, verbose_name='Amenity'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='amount',
            field=apps.hotelbooking.models.EncryptedDecimalField(default=1000.0, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Base Amount'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='contact_number',
            field=fernet_fields.fields.EncryptedCharField(max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='total_person',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Persons'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='total_price',
            field=apps.hotelbooking.models.EncryptedDecimalField(default=1000.0, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='hotelrevenue',
            name='amount',
            field=apps.hotelbooking.models.EncryptedDecimalField(default=1000.0, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='hotelrevenue',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='description',
            field=models.TextField(verbose_name='Room Description'),
        ),
    ]
