# Generated by Django 5.2 on 2025-04-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0004_alter_guide_experience_years_alter_guide_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
