# Generated by Django 5.2 on 2025-04-24 06:00

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0005_alter_hotelbooking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
