# Generated by Django 5.2 on 2025-04-25 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0006_alter_hotelbooking_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelbooking',
            table='hotelbooking',
        ),
    ]
