# Generated by Django 5.1.6 on 2025-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField(unique=True)),
                ('hotel_id', models.IntegerField(blank=True, null=True)),
                ('guide_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
