# Generated by Django 5.2 on 2025-04-22 07:37

import apps.Payments.models
import django.core.validators
import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=apps.Payments.models.EncryptedDecimalField(default=1000.0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='hotel_name',
            field=fernet_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=fernet_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=fernet_fields.fields.EncryptedCharField(max_length=20),
        ),
    ]
