# Generated by Django 5.1.6 on 2025-03-05 08:11

from django.db import migrations, models
from django.core.validators import MinValueValidator

class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=False)),
                ('email', models.EmailField(max_length=100, unique=True, null=False)),
                ('dob', models.DateField(null=True, blank=True)),
                ('gender', models.CharField(
                    max_length=20,
                    choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')],
                    null=False
                )),
                ('about_us', models.CharField(max_length=200, null=False)),
                ('language', models.CharField(max_length=255, null=False)),
                ('payment', models.DecimalField(
                    max_digits=10,
                    decimal_places=2,
                    null=False,
                    validators=[MinValueValidator(0.01)]
                )),
                ('image', models.BinaryField(null=True, blank=True)),
                ('location', models.CharField(max_length=255, null=False)),
                ('phone', models.CharField(max_length=20, null=False)),
                ('experience', models.IntegerField(null=False)),
                ('expertise', models.TextField(null=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Guides',
            },
        ),
    ]