# Generated by Django 5.1.6 on 2025-03-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='expertise',
            field=models.TextField(default='No expertise specified'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='guide',
            table=None,
        ),
    ]
