# Generated by Django 5.2 on 2025-04-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0003_alter_guide_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guides/'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Nepali', 'Nepali'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('Chinese', 'Chinese'), ('German', 'German'), ('Japanese', 'Japanese')], default='Nepali', max_length=50),
        ),
        migrations.AlterField(
            model_name='guide',
            name='location',
            field=models.CharField(choices=[('Nepal - Kathmandu', 'Nepal - Kathmandu'), ('Nepal - Pokhara', 'Nepal - Pokhara'), ('Nepal - Chitwan', 'Nepal - Chitwan'), ('Nepal - Lumbini', 'Nepal - Lumbini'), ('India - Delhi', 'India - Delhi'), ('India - Mumbai', 'India - Mumbai'), ('India - Jaipur', 'India - Jaipur'), ('USA - New York', 'USA - New York'), ('USA - Los Angeles', 'USA - Los Angeles')], default='Nepal - Kathmandu', max_length=100),
        ),
    ]
