# Generated by Django 5.2 on 2025-04-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0004_alter_guide_image_alter_guide_language_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guide',
            table='Guides',
        ),
    ]
