# Generated by Django 5.2 on 2025-04-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0005_alter_guide_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='payment',
            new_name='amount',
        ),
    ]
