# Generated by Django 5.2 on 2025-04-07 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0006_rename_payment_guide_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='amount',
            new_name='payment',
        ),
    ]
