# Generated by Django 5.2 on 2025-04-16 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0007_alter_guide_amount_rename_amount_guide_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the spoken language.', max_length=50, unique=True, verbose_name='Language')),
            ],
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Tour Guide', 'verbose_name_plural': 'Tour Guides'},
        ),
        migrations.RemoveField(
            model_name='guide',
            name='guide_id',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='language',
        ),
        migrations.AddField(
            model_name='guide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='guide',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture.', upload_to='guide_profiles/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='guide',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Average rating (0.0–5.0) from reviews.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='about_us',
            field=models.CharField(help_text='Brief summary about the guide.', max_length=200, verbose_name='About the Guide'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the guide was added.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='dob',
            field=models.DateField(blank=True, help_text="Enter the guide's birth date.", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.EmailField(help_text='Enter a valid and unique email.', max_length=100, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='experience',
            field=models.IntegerField(help_text='Number of years the guide has been active (0–60).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='expertise',
            field=models.TextField(help_text="Enter the guide's key strengths, regions, or specialties.", verbose_name='Areas of Expertise'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text="Select the guide's gender.", max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional additional guide image.', null=True, upload_to='guides/', verbose_name='Additional Image'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='location',
            field=models.CharField(choices=[('Nepal - Kathmandu', 'Nepal - Kathmandu'), ('Nepal - Pokhara', 'Nepal - Pokhara'), ('Nepal - Chitwan', 'Nepal - Chitwan'), ('Nepal - Lumbini', 'Nepal - Lumbini'), ('India - Delhi', 'India - Delhi'), ('India - Mumbai', 'India - Mumbai'), ('India - Jaipur', 'India - Jaipur'), ('USA - New York', 'USA - New York'), ('USA - Los Angeles', 'USA - Los Angeles')], help_text="Select the guide's operating location.", max_length=100, verbose_name='Base Location'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(help_text='Enter the full name.', max_length=100, unique=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='payment',
            field=models.DecimalField(decimal_places=2, help_text='Set the standard rate per assignment.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Payment Rate'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='phone',
            field=models.CharField(help_text='Enter a valid contact number.', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Enter a valid phone number.')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='guide',
            name='languages',
            field=models.ManyToManyField(help_text='Select all languages spoken by the guide.', to='Guides.language', verbose_name='Languages Spoken'),
        ),
    ]
