# Generated by Django 5.2 on 2025-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0008_language_alter_guide_options_remove_guide_guide_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='id',
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
