# Generated by Django 5.2 on 2025-04-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0009_remove_guide_id_guide_guide_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_id',
            field=models.IntegerField(unique=True),
        ),
    ]
