# Generated by Django 5.2 on 2025-04-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0010_guide_id_alter_guide_guide_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='id',
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
