# Generated by Django 5.2 on 2025-04-17 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0011_remove_guide_id_alter_guide_guide_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='guide',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Set the standard rate per assignment.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Payment Rate'),
        ),
        migrations.AddField(
            model_name='guide',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated slug from name', null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.BinaryField(blank=True, help_text="Guide's image stored as binary data.", null=True, verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='languages',
            field=models.ManyToManyField(help_text='Comma-separated languages spoken by the guide.', to='Guides.language', verbose_name='Languages Spoken'),
        ),
    ]
