# Generated by Django 5.2 on 2025-04-22 07:37

import apps.Guides.models
import django.core.validators
import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0012_remove_guide_payment_remove_guide_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='about_us',
            field=fernet_fields.fields.EncryptedCharField(help_text='Brief summary about the guide.', max_length=200, verbose_name='About the Guide'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='amount',
            field=apps.Guides.models.EncryptedDecimalField(default=1000.0, help_text='Set the standard rate per assignment.', validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Payment Rate'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(help_text='Enter a valid and unique email.', max_length=100, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='expertise',
            field=fernet_fields.fields.EncryptedTextField(help_text="Enter the guide's key strengths, regions, or specialties.", verbose_name='Areas of Expertise'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=fernet_fields.fields.EncryptedCharField(help_text='Enter the full name.', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='phone',
            field=fernet_fields.fields.EncryptedCharField(help_text='Enter a valid contact number.', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Enter a valid phone number.')], verbose_name='Phone Number'),
        ),
    ]
