# Generated by Django 5.2 on 2025-04-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0013_alter_guide_about_us_alter_guide_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, help_text="Guide's image stored as binary data.", null=True, upload_to='', verbose_name='Profile Image'),
        ),
    ]
