# Generated by Django 5.2 on 2025-04-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0014_alter_guide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='rating',
        ),
    ]
