# Generated by Django 5.2 on 2025-04-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0015_remove_guide_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='slug',
        ),
    ]
