# Generated by Django 5.2 on 2025-04-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0016_remove_guide_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guide',
            table=None,
        ),
    ]
