# Generated by Django 5.2 on 2025-04-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0017_alter_guide_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guide',
            table='Guides',
        ),
        migrations.AlterModelTable(
            name='language',
            table='guides_languages',
        ),
    ]
