# Generated by Django 5.2 on 2025-04-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0018_alter_guide_table_alter_language_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guide',
            table=None,
        ),
    ]
