# Generated by Django 5.2 on 2025-04-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0019_alter_guide_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='language',
            table=None,
        ),
    ]
