# Generated by Django 5.2 on 2025-05-11 06:54

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0020_alter_language_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='languages',
        ),
        migrations.AddField(
            model_name='guide',
            name='language',
            field=fernet_fields.fields.EncryptedCharField(default='English', help_text='Comma-separated list of languages.', max_length=255, verbose_name='Languages Spoken'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
