# Generated by Django 5.2 on 2025-05-18 06:57

import apps.Guides.models
import django.core.validators
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0021_remove_guide_languages_guide_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='amount',
            field=apps.Guides.models.EncryptedDecimalField(default=Decimal('1000.00'), help_text='Set the standard rate per assignment.', validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Payment Rate'),
        ),
    ]
