# Generated by Django 5.2 on 2025-05-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0022_alter_guide_amount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guide',
            table='guides_guide',
        ),
    ]
