# Generated by Django 5.1.6 on 2025-03-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0002_tourpackage_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='description',
            field=models.TextField(),
        ),
    ]
