# Generated by Django 5.1.6 on 2025-03-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0003_alter_tourpackage_date_alter_tourpackage_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourpackage',
            table='TourPackage',
        ),
    ]
