# Generated by Django 5.1.6 on 2025-03-06 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guides', '0001_initial'),
        ('hotelbooking', '0001_initial'),
        ('tour_package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('total_members', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('booking_details', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('promecode', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guides.guide')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.hotelbooking')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_package.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
