# Generated by Django 5.2 on 2025-04-20 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0012_remove_guide_payment_remove_guide_profile_picture_and_more'),
        ('bookings', '0005_alter_booking_user'),
        ('hotelbooking', '0003_language_alter_hotelbooking_options_and_more'),
        ('tour_package', '0008_alter_tourpackage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(help_text='Date when the booking was made.', verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_details',
            field=models.CharField(blank=True, help_text='Additional details or notes about the booking.', max_length=255, null=True, verbose_name='Booking Details'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(help_text='Unique identifier for the booking.', primary_key=True, serialize=False, verbose_name='Booking ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guide',
            field=models.ForeignKey(blank=True, help_text='Tour guide assigned to the booking, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guides.guide', verbose_name='Guide'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Associated hotel booking, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.hotelbooking', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(help_text='Tour package selected by the user.', on_delete=django.db.models.deletion.CASCADE, to='tour_package.tourpackage', verbose_name='Tour Package'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(help_text='Phone number of the user.', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(help_text='Location where the customer will be picked up.', max_length=255, verbose_name='Pickup Location'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='promecode',
            field=models.CharField(blank=True, help_text='Applied promo code for discount, if any.', max_length=50, null=True, verbose_name='Promo Code'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the booking.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_members',
            field=models.IntegerField(help_text='Number of people included in the booking.', verbose_name='Total Members'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='User who made the booking.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(help_text='Name of the user who booked the package.', max_length=255, verbose_name='User Name'),
        ),
    ]
