# Generated by Django 5.2 on 2025-04-22 07:37

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_options_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_details',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='Additional details or notes about the booking.', max_length=255, null=True, verbose_name='Booking Details'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=fernet_fields.fields.EncryptedCharField(help_text='Phone number of the user.', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=fernet_fields.fields.EncryptedCharField(help_text='Location where the customer will be picked up.', max_length=255, verbose_name='Pickup Location'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=fernet_fields.fields.EncryptedCharField(help_text='Name of the user who booked the package.', max_length=255, verbose_name='User Name'),
        ),
    ]
