# Generated by Django 5.2 on 2025-04-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_company', '0002_alter_tourismcompany_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismcompany',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourismcompany',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
