# Generated by Django 5.2 on 2025-04-11 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_company', '0003_tourismcompany_is_active_tourismcompany_password'),
        ('user_login', '0012_rename_booking_bookingdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismcompany',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_login.user'),
        ),
    ]
