# Generated by Django 5.2 on 2025-04-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_company', '0004_tourismcompany_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourismcompany',
            name='user',
        ),
    ]
