# Generated by Django 5.2 on 2025-04-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_company', '0005_remove_tourismcompany_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourismcompany',
            options={'verbose_name': 'Tourism Company', 'verbose_name_plural': 'Tourism Companies'},
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='company_address',
            field=models.CharField(help_text='Address of the company.', max_length=255, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='company_id',
            field=models.AutoField(help_text='Unique identifier for the tourism company.', primary_key=True, serialize=False, verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='company_name',
            field=models.CharField(help_text='Name of the tourism company.', max_length=255, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='company_phone',
            field=models.CharField(help_text='Contact number of the company.', max_length=20, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the company account is active.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='password',
            field=models.CharField(help_text='Password for the company account (should be hashed).', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='user_email',
            field=models.EmailField(help_text='Email of the user (must be unique).', max_length=55, unique=True, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='user_name',
            field=models.CharField(help_text='Name of the user who owns the company.', max_length=100, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='user_phone',
            field=models.CharField(help_text='Contact number of the user.', max_length=20, verbose_name='User Phone'),
        ),
        migrations.AlterModelTable(
            name='tourismcompany',
            table='tourism_company_tourismcompany',
        ),
    ]
