# Generated by Django 5.2 on 2025-04-22 07:37

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_company', '0006_alter_tourismcompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismcompany',
            name='company_address',
            field=fernet_fields.fields.EncryptedCharField(help_text='Address of the company.', max_length=255, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='user_email',
            field=fernet_fields.fields.EncryptedEmailField(help_text='Email of the user (must be unique).', max_length=55, verbose_name='User Email'),
        ),
    ]
