# Generated by Django 5.2 on 2025-05-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_company', '0008_alter_tourismcompany_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismcompany',
            name='user_email',
            field=models.EmailField(help_text='Email of the user (must be unique).', max_length=254, verbose_name='User Email'),
        ),
    ]
