# Generated by Django 5.1.6 on 2025-03-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_type', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hotel_photos/')),
                ('hotel_address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('total_person', models.IntegerField()),
                ('arrive_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
