# Generated by Django 5.2 on 2025-04-20 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_community', '0007_remove_post_group'),
        ('social_stories', '0002_comment_image'),
        ('user_login', '0015_language_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='travelnews',
            options={'ordering': ['-created_at'], 'verbose_name': 'Travel News', 'verbose_name_plural': 'Travel News'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(help_text='User who wrote the article.', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='user_login.user', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='social_community.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Main content of the article.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the article was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the article.', null=True, upload_to='articles/images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Title of the article.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the article was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Article on which the comment was made.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_stories.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Content of the comment.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was made.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the comment.', null=True, upload_to='comment_images/', verbose_name='Comment Image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Post on which the comment was made.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_community.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='User who made the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_login.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Article that was liked.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social_stories.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the like was made.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Post that was liked.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social_community.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(help_text='User who liked the post or article.', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='user_login.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='travelnews',
            name='content',
            field=models.TextField(help_text='Content of the travel news.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='travelnews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the news was published.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='travelnews',
            name='source',
            field=models.URLField(blank=True, help_text='Optional source link of the news.', null=True, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='travelnews',
            name='title',
            field=models.CharField(help_text='Title of the travel news.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='article_article',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='article_comment',
        ),
        migrations.AlterModelTable(
            name='like',
            table='article_like',
        ),
        migrations.AlterModelTable(
            name='travelnews',
            table='article_travelnews',
        ),
    ]
