# Generated by Django 5.2 on 2025-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stories', '0004_alter_article_content_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Content of the comment.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was made.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the like was made.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='travelnews',
            name='content',
            field=models.TextField(help_text='Content of the travel news.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='travelnews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the news was published.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='travelnews',
            name='title',
            field=models.CharField(help_text='Title of the travel news.', max_length=200, verbose_name='Title'),
        ),
    ]
