# Generated by Django 5.2 on 2025-05-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stories', '0005_alter_comment_content_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the article was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the article was last updated.', verbose_name='Updated At'),
        ),
    ]
