# Generated by Django 5.1.6 on 2025-04-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='Bookings',
        ),
    ]
