# Generated by Django 5.2 on 2025-04-18 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0012_remove_guide_payment_remove_guide_profile_picture_and_more'),
        ('hotelbooking', '0002_hotelrevenue_hotelbooking_amenity_hotelbooking_email_and_more'),
        ('reviews', '0002_remove_review_id_review_review_id_alter_review_table'),
        ('tour_package', '0007_alter_tourpackage_company'),
        ('tourism_company', '0005_remove_tourismcompany_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Optional tourism company being reviewed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism_company.tourismcompany', verbose_name='Tourism Company'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created.', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='guide',
            field=models.ForeignKey(blank=True, help_text='Optional guide being reviewed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='Guides.guide', verbose_name='Guide'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Optional hotel booking being reviewed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.hotelbooking', verbose_name='Hotel Booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Optional tour package being reviewed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_package.tourpackage', verbose_name='Tour Package'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo for the review.', null=True, upload_to='reviews/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Select a rating from 1 to 5 stars.', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, help_text='Optional review comments.', null=True, verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='Select the user who submitted the review.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
