# Generated by Django 5.2 on 2025-04-20 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0012_remove_guide_payment_remove_guide_profile_picture_and_more'),
        ('hotelbooking', '0003_language_alter_hotelbooking_options_and_more'),
        ('reviews', '0003_alter_review_company_alter_review_created_at_and_more'),
        ('tour_package', '0008_alter_tourpackage_options_and_more'),
        ('tourism_company', '0006_alter_tourismcompany_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the review was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Tourism company being reviewed, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='tourism_company.tourismcompany', verbose_name='Tourism Company'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the review was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='guide',
            field=models.ForeignKey(blank=True, help_text='Guide being reviewed, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='Guides.guide', verbose_name='Guide'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel booking being reviewed, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='hotelbooking.hotelbooking', verbose_name='Hotel Booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Tour package being reviewed, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='tour_package.tourpackage', verbose_name='Tour Package'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo uploaded with the review.', null=True, upload_to='reviews/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5 stars.', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, help_text='Detailed review comments.', null=True, verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='User who submitted the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='Reviews_user_id_5272e6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['company'], name='Reviews_company_90eb85_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='Reviews_created_00ac17_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='valid_rating_range'),
        ),
    ]
