# Generated by Django 5.2 on 2025-04-22 07:37

import django.core.validators
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo uploaded with the review (JPG/PNG only, max 5MB).', null=True, upload_to='reviews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Detailed review comments.', null=True, verbose_name='Review Text'),
        ),
    ]
