# Generated by Django 5.1.6 on 2025-03-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0004_remove_booking_user_id_booking_user_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='Wishlist',
        ),
    ]
